# =========================
# Card Sorter Configuration
# =========================

# -------------------------
# Camera settings
# -------------------------
camera:
  # device:            # keep commented
  resolution: [1280, 720]
  preview_fps: 5


# -------------------------
# OCR settings
# -------------------------
ocr:
  engine: tesseract
  lang: eng
  psm: 6              # Assume a single uniform block of text
  oem: 3              # Default LSTM OCR engine

  # Confidence settings
  min_confidence: 75  # Raise minimum confidence (0–100)
  max_results: 5      # Only return top 5 strongest detections

  # Image preprocessing
  preprocess:
    grayscale: true
    threshold: true
    denoise: true
    sharpen: true
    resize: 1.5       # Scale up image for better OCR accuracy

  # Region of interest prioritization
  roi:
    mode: top_priority
    top_fraction: 0.35   # Give highest priority to top 35% of the image
    fallback_full: true  # If no confident result in top, use full image scan

  # Debugging / logging
  save_debug: true       # Save intermediate processed images
  log_text_output: true  # Print detected text with confidence


# -------------------------
# Assignment (slot mapping) settings
# -------------------------
assignment:
  mode: "first_letter"
  slots_csv: "slots.csv"
  default_slot: null
  first_letter_groups: {}   # empty map is valid



# -------------------------
# Grid settings for MPCNC slot positions
# -------------------------
grid:
  origin_mm: [0.0, 0.0]      # Machine coordinates (X0,Y0) for slot (row=0,col=0) center
  pitch_mm: [70.0, 95.0]     # Distance between slot centers (X, Y) in mm
  rows: 5
  cols: 10
  z:
    pick: -2.0               # Z height for picking/placing card
    travel: 15.0             # Z height for moving between slots
    safe: 20.0               # Z height for safe clearance above all slots

# -------------------------
# Motion (MPCNC / SKR Pro) settings
# -------------------------
motion:
  port: "/dev/ttyACM0"     # adjust if your SKR shows as ttyUSB0, etc.
  baud: 250000
  enabled: false           # you can enable from the UI/endpoint
  read_timeout_s: 2.0
  write_timeout_s: 2.0
  connect_timeout_s: 6.0
  reset_on_connect: true
  startup_drain_s: 2.0
  ok_tokens: ["ok"]
  error_tokens: ["error", "Error:"]
  busy_tokens: ["busy:", "wait"]


# -------------------------
# Plunger (vacuum head stepper) settings
# -------------------------
plunger:
  enable_pin: 18              # BCM numbering
  step_pin: 23
  dir_pin: 24
  enable_active_low: true
  dir_invert: false
  backend: null               # null = auto, or "pigpio" / "rpigpio"

# -------------------------
# Server & logging
# -------------------------
server:
  host: "0.0.0.0"
  port: 8000

logging:
  level: "INFO"               # DEBUG, INFO, WARNING, ERROR

cors:
  allow_origins: ["*"]        # CORS allowlist for web UI connections
